name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Dependency Versions - Dependency Updates
        run: ./gradlew dependencyUpdates
      - name: Build - Assemble (Debug)
        run: ./gradlew assembleDebug
      - name: Dependency Analysis - Build Health
        run: ./gradlew assembleDebug
      - name: Static Analysis - Detekt
        run: ./gradlew detekt
      - name: Static Analysis - Lint (Debug)
        run: ./gradlew lintDebug
      - name: Test - Unit Test - Kotlin Modules
        run: ./gradlew test -x testDebugUnitTest -x testReleaseUnitTest
      - name: Test - Unit Test - Android Modules (Debug)
        run: ./gradlew testDebugUnitTest
      - name: Test - Unit Test - Code Coverage
        run: ./gradlew testDebugUnitTest
      - name: Test - UI Test - App Module (Debug)
        run: ./gradlew app:connectedDebugAndroidTest
