name: Android CI

on:
  push:

jobs:
  validate:
    strategy:
      matrix:
        version: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Validate Dependency Versions
        run: ./gradlew dependencyUpdates
  build:
    strategy:
      matrix:
        version: [ 17 ]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build - Assemble (Debug)
        run: ./gradlew assembleDebug
      - name: Dependency Analysis - Build Health
        run: ./gradlew buildHealth
      - name: Static Analysis - Detekt without Type Resolution
        run: ./gradlew detekt
      - name: Static Analysis - Detekt with Type Resolution (Main)
        run: ./gradlew detektMain
      - name: Static Analysis - Detekt with Type Resolution (Test)
        run: ./gradlew detektTest
      - name: Static Analysis - Lint (Debug)
        run: ./gradlew lintDebug
      - name: Test - Unit Test - Kotlin Modules
        run: ./gradlew test -x testDebugUnitTest -x testReleaseUnitTest
      - name: Test - Unit Test - Android Modules (Debug)
        run: ./gradlew testDebugUnitTest
      - name: Test - Unit Test - Code Coverage
        run: ./gradlew jacoco
      - name: Test - Assemble UI Test - App Module (Debug)
        run: ./gradlew app:assembleDebugAndroidTest
  test:
    strategy:
      matrix:
        version: [ 17 ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Test - UI Test - App Module (Debug)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew app:connectedDebugAndroidTest
